### ISSUE TITLE
Mehr Zeitpunkte für Helligkeitssteuerung

### ISSUE THREAD

**Issue by m50434** [xXBJXx/ioBroker.fully-tablet-control#11]
Ich fände es praktisch, wenn man in der Helligkeitssteuerung einen etwas flexibleren Zeitplan einstellen könnte und nicht nur zwei Zeiten (morgens und abends) wählbar sein.

Bespiel:
Abends ab 18 Uhr Helligkeit 30 %
ab 21 Uhr 10 %
ab 23 Uhr 1%

Hängt natürlich individuell von den Lichtverhältnissen des jeweiligen Tablet-Standortes ab, aber gerade in den Wintermonaten (wenn es früher dunkel wird) ist das sicherlich auch nochmal eine Einstellung, die man gut gebrauchen könnte.

**Comment by xXBJXx** [comment]
Ich schau mal wie ich das noch dazu einbauen kann das würde ich dann zu der Manuelle Zeit hinzufügen.

**Comment by xXBJXx** [comment]
Ich werde die Manuelle Zeit Steuerung um eins erweitern das wird dann so aussehen morgens /   mittags / abends
![Screenshot_235](https://user-images.githubusercontent.com/32600934/94349319-b0907c80-0043-11eb-990b-8b70863c2625.png)
3 oder mehr Einstellungen z.B. nur für den Abend werde ich nicht einbauen das kann jeder über ein kleines script selbst einstellen dafür ist der manualBrightness state da.

**Comment by xXBJXx** [comment]
in Version 3.0.0 integriert
