### ISSUE TITLE
warning because of (has no existing object) with the JS controller v3.2.4

### ISSUE THREAD

**Issue by xXBJXx** [xXBJXx/ioBroker.fully-tablet-control#114]
`State "fully-tablet-control.0.device.test.brightness_control_mode" has no existing object, this might lead to an error in future versions`

**Comment by Feuer-sturm** [comment]
Bei mir kam gerade mit js-controller 3.2.6-0 und fully tablet control v0.2.15 folgende Warnung:


```
fully-tablet-control.0 | 2021-01-14 22:41:05.716 | warn | (1105) State  "fully-tablet-control.0.device.Wandtablet.charging_warning" has no  existing object, this might lead to an error in future versions
fully-tablet-control.0 | 2021-01-14 22:41:05.714 | warn | (1105) State "h" has no existing object, this might lead to an error in future versions
```

**Comment by xXBJXx** [comment]
@Feuer-sturm installiere mal die neuste Version seit der v0.2.15 hat sich einiges geändert schau dann noch mal ob was kommt da was kommt

**Comment by Feuer-sturm** [comment]
@xXBJXx ich hab die 0.2.15 im Einsatz. Mit der Version ist es aufgefallen.

**Comment by Feuer-sturm** [comment]
@xXBJXx ok. Habe jetzt 0.3.1-beta.2 installiert und werde es beobachten.

**Comment by Feuer-sturm** [comment]
Seit dem Update auf 0.3.1-beta.2 hab ich keine Warnungen mehr im Log gefunden :-)

**Comment by xXBJXx** [comment]
fixed in v0.3.2-beta.0
