### ISSUE TITLE
Feature: Video

### ISSUE THREAD

**Issue by duczz** [xXBJXx/ioBroker.fully-tablet-control#127]
Derzeit kann man ja bereits camshot machen, wäre sowas auch für Videos möglich? Sprich eine Video Aufnahme zu starten mit Angabe einer gewissen Dauer?

Der Camshot scheint aktuell auch nicht zu gehn?

**Comment by xXBJXx** [comment]
Ich habe grade den camshot getestet er funktioniert mit adapter version 0.3.2-beta.0 Samsung Tablet.
und zu der Video frage kann ich dir nur sagen nein da es nicht möglich ist von dem fully Browser ein video aufzunähen ob das möglich sein wird must du den Entwickler vom fully Browser fragen

**Comment by duczz** [comment]
auf der selben version bin ich auch und es wird kein bild unter "/fully-tablet-control.admin/media/camshot_eingang_0.png" abgelegt

**Comment by xXBJXx** [comment]
hast du auch den motionDetection unter command aktiviert? und ist der camshot64 auch nicht da?

**Comment by duczz** [comment]
Jup hab ich, der camshot64 funktioniert

**Comment by xXBJXx** [comment]
dann sollte der normale auch funktionieren ist die selbe Funktion

**Comment by duczz** [comment]
hab ich bereits, da liegt nix drin

**Comment by xXBJXx** [comment]
hast du heute mittag so gegen 14 Uhr zeit dan schaue ich bei dir per discord einfach mal nach

**Comment by duczz** [comment]
Jup, sollte klappen - danke

**Comment by duczz** [comment]
Close, Camshot erzeugung war ein Bug in meiner ioBroker Umgebung
