### ISSUE TITLE
Camshot Counter

### ISSUE THREAD

**Issue by duczz** [xXBJXx/ioBroker.fully-tablet-control#129]
Wäre es möglich das der Camshot nicht nur immer ein fixes Bild abliegt sondern mehrere *_0, *_1, *_2. 
Der Counter könnte dann Mitternacht resetet werden.

Somit könnte man ihn als Alarmanlagen Camshot nutzen.

Evtl. wäre dann auch OID gut welcher die angelegten Camshotnamen Anzeigt (*_0, *.1, *_2)

**Comment by xXBJXx** [comment]
ich werde versuchen es bis nächstes Wochenende einzubauen.
Was genau meinst du mit
> wäre dann auch OID gut welcher die angelegten Camshotnamen Anzeigt

meinst du ein drop down Menu in den Objecten ?

**Comment by duczz** [comment]
Ich mein einen Datenpunkt, welcher alle Camshot Dateinamen mit aufführt

**Comment by xXBJXx** [comment]
ich kann sie in eine Json packen die dann in etwa so aus schaut 
``` js
{"0": "/fully-tablet-control.admin/media/camshot_samsung_galaxy_s4_vis_0.png","1": "/fully-tablet-control.admin/media/camshot_samsung_galaxy_s4_vis_1.png", usw.}
```
wäre das was?

**Comment by duczz** [comment]
Wäre Top :)

**Comment by xXBJXx** [comment]
Erweiterung in v0.3.3-beta.0 hinzugefügt
