### ISSUE TITLE
Fehlermeldung wenn Screensaver deaktiviert

### ISSUE THREAD

**Issue by Chaot1** [xXBJXx/ioBroker.fully-tablet-control#161]
Ich habe seit dem Update auf die letzte Betaversion eine Fehlermeldung die scheinbar durch die Screensafer Steuerung ausgelöst wird:
`

fully-tablet-control.0 | 14532 | 2021-04-20 08:36:38.338 | error | zeroPad has a problem: Cannot read property 'toString' of undefined, stack: TypeError: Cannot read property 'toString' of undefined at FullyTabletControl.zeroPad (/opt/iobroker/node_modules/iobroker.fully-tablet-control/main.js:3337:37) at FullyTabletControl.astroTime (/opt/iobroker/node_modules/iobroker.fully-tablet-control/main.js:1953:40) at FullyTabletControl.onReady (/opt/iobroker/node_modules/iobroker.fully-tablet-control/main.js:107:9)
-- | -- | -- | -- | --
fully-tablet-control.0 | 14532 | 2021-04-20 08:36:37.585 | error | Screensaver init funktion has a problem: Unexpected token u in JSON at position 0, stack: SyntaxError: Unexpected token u in JSON at position 0 at JSON.parse (<anonymous>) at FullyTabletControl.initialization (/opt/iobroker/node_modules/iobroker.fully-tablet-control/main.js:436:50) at FullyTabletControl.onReady (/opt/iobroker/node_modules/iobroker.fully-tablet-control/main.js:105:9)
host.ioBroker |   | 2021-04-20 08:36:35.510 | info | instance system.adapter.fully-tablet-control.0 started with pid 14532

`
Adapter V. 0.3.3-beta0
Admin: 5.0.5

**Comment by xXBJXx** [comment]
wie sieht den deine Konfiguration von den Adapter aus ich habe die selben Versionen bei mir ausprobiert und keinerlei Probleme gehabt.
Bitte kontrolliere diese Einstellungen ob da auch alles ausgefüllt ist wen nicht wähle da bitte was aus.
![Screenshot_139](https://user-images.githubusercontent.com/32600934/115430060-52f09700-a204-11eb-9dd0-f6aac81fd548.png)
![Screenshot_138](https://user-images.githubusercontent.com/32600934/115430071-54ba5a80-a204-11eb-80c8-98c0fa350bb2.png)

hals da alles ausgefüllt ist mache bitte ein paar Bilder von deiner config damit ich es bei mir auch so einstellen kann um es bei mir zu testen.

Adapter V. 0.3.3-beta0
Admin: 5.0.5

**Comment by Chaot1** [comment]
![fully1](https://user-images.githubusercontent.com/37418118/115437767-e037e980-a20c-11eb-81a6-a97b97d8161d.jpg)

![fully2](https://user-images.githubusercontent.com/37418118/115437931-15dcd280-a20d-11eb-9ad9-5dfbbfc58003.jpg)


Den Menuepunkt manual Deletion habe ich gar nicht. Egal wie ich das anstelle.

**Comment by xXBJXx** [comment]
du hast aber noch eine alte Version installiere mal von GitHub da ist niemals die V. 0.3.3-beta0  https://github.com/xXBJXx/ioBroker.fully-tablet-control

**Comment by Chaot1** [comment]
Oh Shit - ich habe das dreimal installiert und es hat scheinbar nie richtig geklappt. Jetzt habe ich komplett deinstalliert und neu installiert und es scheint zu funktionieren. 
Danke für deine Hilfe.

**Comment by xXBJXx** [comment]
in manchen fällen hilft es nach der Installation ein Upload zu machen wen sich viel an der config Seite geändert hat
