### ISSUE TITLE
js-controller 3.3.x

### ISSUE THREAD

**Issue by o0shojo0o** [xXBJXx/ioBroker.fully-tablet-control#164]
![image](https://user-images.githubusercontent.com/19333515/116661475-c75dcf80-a994-11eb-95eb-efafa404de2b.png)

**Comment by kueppert** [comment]
anbei als Text:

fully-tablet-control.0 | 2021-04-30 10:30:31.213 | warn | (18430) State value to set for "fully-tablet-control.0.device.firehd7_flur_eg.device_info.displayWidthPixels" has wrong type "number" but has to be "string"
fully-tablet-control.0 | 2021-04-30 10:30:31.212 | warn | (18430) State value to set for "fully-tablet-control.0.device.firehd7_flur_eg.device_info.displayHeightPixels" has wrong type "number" but has to be "string"

**Comment by xXBJXx** [comment]
fix ist auf GitHub und npm

**Comment by Feuer-sturm** [comment]
@xXBJXx Habe gerade 0.3.4-0  von github installiert. Warning kommt nicht mehr :) Dankeschön.

**Comment by o0shojo0o** [comment]
Kann ich bestätigen und Close :)
