### ISSUE TITLE
Js-Controller 3.3.11 (State "s" has no existing)

### ISSUE THREAD

**Issue by crunchip77** [xXBJXx/ioBroker.fully-tablet-control#184]
mit dem neuen JS -Controller tauchen folgende Meldungen auf, die Zweite Meldung kam schon öfter mal vor, obwohl das Laden funktioniert
eingestellt ist Ladestart 20%, Ladestopp 95%
`

fully-tablet-control.0 | 2021-05-24 10:35:15.307 | warn | (22378) State "s" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
fully-tablet-control.0 | 2021-05-24 10:35:15.256 | warn | (22378) 24.05.21 10:35 hd10firewz Tablet charging function has detected a malfunction, the tablet is not charging, please check it !!!

fully-tablet-control.0 | 2021-05-24 10:45:22.078 | warn | (22378) 24.05.21 10:45 hd10firewz Tablet is charging the problem has been fixed.
-- | -- | -- | --

`

**Comment by xXBJXx** [comment]
fully-tablet-control.0 | 2021-05-24 10:35:15.256 | warn | (22378) 24.05.21 10:35 hd10firewz Tablet charging function has detected a malfunction, the tablet is not charging, please check it !!!
-- | -- | -- | --
fully-tablet-control.0 | 2021-05-24 10:45:22.078 | warn | (22378) 24.05.21 10:45 hd10firewz Tablet is charging the problem has been fixed.

diese Meldungen kommen immer dann wen der lade zustand unter 18% kommt und wider über 20% kommt.
Wenn sie öfter bei dir auftauchen dann ist vllt der lade Strom zu schwach um das Tablet schnell genug aufzuladen hast du bei der ( Helligkeit's Einstellung unter Absenken beim Laden ) 
![Screenshot_269.png](https://app.gitkraken.com/api/glo/boards/60a456bb214da50011c45fc3/attachments/60abcfdb214da50011c5dd2d)
 etwas eingestellt ? falls nicht trage da mal was ein und schau ob es besser wird. 


fully-tablet-control.0 | 2021-05-24 10:35:15.307 | warn | (22378) State "s" has no existing object, this might lead to an error in future versions
-- | -- | -- | --

Diese Meldung ist mir zwar bekannt aber ich kann kein state finden der nur ( s ) heißt hast du in deinen Objekten ein state der nur  heißt? falls ja mache bitte ein screenshot und poste es mir mal.

**Comment by crunchip77** [comment]
ist bei mir so eingestellt
![image](https://user-images.githubusercontent.com/41550245/119845567-ae036100-bf09-11eb-91c9-1f10d8655ef4.png)

leider nein, gibt keinen state "s", ich hatte es so verstanden, das dieser eben in den Objekten fehlt und daher die Meldung kommt

**Comment by xXBJXx** [comment]
hmm das schaut gut aus must mal den Batterie wert logen und schauen ob er unter 18% fehlt und ob zu der zeit das lade gerät an ist so schaut es bei mir aus 
![Screenshot_278](https://user-images.githubusercontent.com/32600934/119847868-a1800800-bf0b-11eb-9cfd-f1a27822062c.png)

**Comment by crunchip77** [comment]
ok, dann werd ich das mal mitloggen, trat bisher erst 4 mal auf  in den letzten Wochen. Vorher waren da keine Probleme.
Die Meldung kam beim Start, als ich auf den Controller 3.3.11 gewechselt hatte.
Instanz gerade mal neu gestartet, da kommt keine Meldung mehr, sehr seltsam

**Comment by xXBJXx** [comment]
ok ich prüfe grade noch mal den Code der fürs laden zuständig ist ob da eventuell was ist kann ich zwar nicht glauben aber ich prüfe es trotzdem noch mal.

**Comment by crunchip77** [comment]
Ah, cool, also war das sozusagen ein dummer (positiver Zufall).
Trotz alledem, logge ich mal die Daten mit, wollte eh mal sehen, wann geladen, bzw wie lange der Akku hält.
Möglicherweise, liegt das auch an der Kamera, (camshot Funktion im Gebrauch), das ich hier und da den Ladezustand unterschritten hatte

**Comment by xXBJXx** [comment]
Ja ein das war ein positiver Zufall.
wenn die Kamera dauerhaft an ist kann das schon sein das da das Ladegerät Probleme hat das schnell genug abzufangen loge es mal mit. 
bei mir Dauer das laden 4 Std und das entladen 6-7 je nachdem ob Nacht oder tag.
Ich lasse das issue noch bis Sonntag offen falls noch was ist.

**Comment by crunchip77** [comment]
hatte ich noch vergessen zu erwähnen, ansonsten zwecks Laden/Entladen nichts auffälliges gewesen

`

(22109) State value to set for "fully-tablet-control.0.device.hd10firewz.device_info.displayWidthPixels" has to be type "string" but received type "number"
--
(22109) State value to set for "fully-tablet-control.0.device.hd10firewz.device_info.displayHeightPixels" has to be type "string" but received type "number"

`

**Comment by xXBJXx** [comment]
lösche mal die 2 dp sie werden dann richtig erstellt

**Comment by crunchip77** [comment]
Hatte zwecks Meldung, manuell auf number gestellt. Wenn ich beide DP's lösche kommen sie wieder mit string, oder muss ich den Adapter neu von Git ziehen?

**Comment by xXBJXx** [comment]
welche version hast du installiert ?

**Comment by crunchip77** [comment]
0.3.1-beta.1

**Comment by xXBJXx** [comment]
lade mal von git ist bereits 0.3.6

**Comment by crunchip77** [comment]
habs gemerkt, hatte ich gar nicht darauf geachtet, wurde ja schon in 0.3.4 gefixt,
ok, passt nun

**Comment by xXBJXx** [comment]
ich bin grade an einer neuen admin config Seite am bestem sobald die fertig ist und der adapter darauf angepasst wurde werde ich mal schauen das der adapter in die repo kommt kann aber noch ein wenig dauern hab momentan nicht viel zeit dran zu basteln.
So könnte es dan ungefähr ausschauen ist aber noch nicht final
![newGui](https://user-images.githubusercontent.com/32600934/120085361-ce811600-c0d7-11eb-9d36-da9693e677d2.png)

**Comment by crunchip77** [comment]
ja das wäre gut, da man nicht immer darauf achtet, zwecks Version " wie ich in dem Fall :-) "
das siehst viel versprechend aus :+1:

**Comment by xXBJXx** [comment]
da es keine weiteren Probleme gibt schließe ich das issue falls nötig bitte wieder öffnen.
