### ISSUE TITLE
Zeit wählbar für Bildschirmschoner

### ISSUE THREAD

**Issue by crunchip77** [xXBJXx/ioBroker.fully-tablet-control#2]
Aktuell ist für den Bildschirmschoner eine einstellbare Zeit in 5 Minuten Schritten möglich, per Pulldown. Wäre es möglich, die Funktion auf einzelne Minuten zu erweitern, gegebenenfalls die Zeit als Zahl einzugeben.

**Comment by xXBJXx** [comment]
ich werde das Pulldown auf einzelne Minuten erweitern 1 bis 60 min sollte reichen denke ich

**Comment by xXBJXx** [comment]
hab die zeit jetzt in 1 min schritten hinzugefügt
