### ISSUE TITLE
Error Message With Admin 5 and JS Controller 3.3

### ISSUE THREAD

**Issue by jack-blackson** [xXBJXx/ioBroker.fully-tablet-control#222]
Hallo!

Seit dem Upgrade bekomme ich diese Fehlermeldung:
<img width="1274" alt="grafik" src="https://user-images.githubusercontent.com/13975634/128640284-277a7279-0a65-4537-883a-8e1c7db69876.png">

Adapterversion: 0.3.6-1

Könntest du dir das bitte ansehen?

Danke,
Jack

**Comment by xXBJXx** [comment]
lösche die 2 states die werden dann richtig angelegt das ist bereits behoben im issue #164

**Comment by jack-blackson** [comment]
Super - sorry, hab ich nicht gesehen.

**Comment by jack-blackson** [comment]
Diesen Fehler bekomme ich noch, auch wenn ich das Objekt gelöscht habe: 

Read-only state "fully-tablet-control.0.vis_View.Timer_View_Switch" has been written without ack-flag with value "600"

**Comment by xXBJXx** [comment]
Schaue ich mir mal an

**Comment by jack-blackson** [comment]
Ich hab auch das Gefühl, das es seither nicht mehr funktioniert, es springt nicht mehr auf die definierte View zurück - wäre spitze, wenn du hier eine Lösung finden würdest.

**Comment by xXBJXx** [comment]
installiere mall von GitHub hab da ein fix hochgeladen die Versionsnummer ist noch die selbe

**Comment by jack-blackson** [comment]
Die Meldung im Log ist weg, aber der Sprung zurück auf die Startseite klappt leider nicht. 
![grafik](https://user-images.githubusercontent.com/13975634/128971979-d9715cdc-6b5b-4f04-b5f8-16f8aae83252.png)
So ist mein Setup. Der Timer verändert sich aber auch nie, der bleibt immer auf 0 stehen.

**Comment by xXBJXx** [comment]
Ich testet es heute mittag mal mit deinen Einstellungen von dem Screenshot

**Comment by xXBJXx** [comment]
Ich habe das Problem gefunden und im Grunde ist es auch kein Problem von der Funktion da die Funktion so wie es bei dir eingetragen ist nicht funktionieren kann die Funktion funktioniert so:
1. Home view = Main => zeit 00 sec
2. Wetter view = Wetter => zeit 30 sec
3. Heizung view = Heizung => 40 sec

so jetzt macht die Funktion folgendes:
sobald der state (vis.0.control.data) sich ändert z.B. auf Wetter dann wird die Zeit von dieser view genommen also die 30 sec nach der Zeit wird die View Main angezeigt und da diese view keine Zeit hat bleibt sie dauerhaft an und der Timer läuft nicht

bei deiner Einstellung ist es jetzt so:
Du hast nur deine Main View mit zeit eingestellt das bedeutet das der Adapter dauerhaft mit dem Timer läuft da er ja nach der Zeit an den vis Adapter ein command sendet um die view zu wechseln und der vis Adapter bestätigt das dann somit hat sich der state ( vis.0.control.data ) wider geändert und das ganze geht wieder von vorne los.
Dabei gibt es auch ein Problem das die Funktion nicht immer erkennt ob sich die view geändert hat da sie die view's nicht kennt.

Ich würde dir mal vorschlagen das du deine view's in die Liste einträgst und es dann noch mal Probierst die Oberste view z.B. auf dem Bild Main ist die Home View die muss mit 00 sec sein.

**Comment by jack-blackson** [comment]
Danke erstmals fürs Testen. Ich weiß nicht sicher, ob ich das Feature von dir richtig nutze. Mein Ziel ist es, das immer wenn ich zum Tablet komme der View Main ausgewählt ist, egal was ich vorher hatte. Sprich ich gehe hin, wechsle von Main auf Wetter, und dann sollte es nach Zeit X wieder automatisch auf Main gehen. Hast du dir diese Funktion anderst vorgestellt?

**Comment by xXBJXx** [comment]
genau das ist das ziel der Funktion nur darf die Main view nicht alleine drin stehen es müssen alle view drin sein die aufgerufen werden können und die mit der zeit versehen werden die Main view muss dabei immer mit 0sec angegeben sein sonst läuft sie in eine schleife z.B. so wie hier auf den Bild
![Screenshot_2610](https://user-images.githubusercontent.com/32600934/129359281-06d5aeac-4038-421e-8323-f72af51c2fae.png)

**Comment by jack-blackson** [comment]
Das klappt gut - danke!
