### ISSUE TITLE
type "string" but received type "number"

### ISSUE THREAD

**Issue by sigi2345** [xXBJXx/ioBroker.fully-tablet-control#225]
Hallo,  bekomme das:

`
<html>
<body>

fully-tablet-control.0 | 2021-08-12 10:22:10.944 | warn | Automatic brightness for samsung_tab is activated but no configuration is entered, the manual mode is activated.
-- | -- | -- | --
fully-tablet-control.0 | 2021-08-12 10:22:10.938 | info | State value to set for "fully-tablet-control.0.device.samsung_tab.device_info.displayWidthPixels" has to be type "string" but received type "number"
fully-tablet-control.0 | 2021-08-12 10:22:10.938 | info | State value to set for "fully-tablet-control.0.device.samsung_tab.device_info.displayHeightPixels" has to be type "string" but received type "number"
fully-tablet-control.0 | 2021-08-12 10:22:10.602 | info | starting. Version 0.3.6-1 in C:/Program Files/iobroker/Home/node_modules/iobroker.fully-tablet-control, node: v12.22.5, js-controller: 3.3.15

</body>
</html>`

**Comment by xXBJXx** [comment]
lösche die 2 states die werden dann richtig angelegt das ist bereits behoben im issue #164
