### ISSUE TITLE
Automatic brightness for eingang is activated but no configuration is entered, the manual mode is activated.

### ISSUE THREAD

**Issue by duczz** [xXBJXx/ioBroker.fully-tablet-control#398]
Hallo,

wie bekomm ich den Fehler weg? Welche Configuration ist da gemeint?
`Automatic brightness for eingang is activated but no configuration is entered, the manual mode is activated.`

![image](https://user-images.githubusercontent.com/25475385/196039432-f1d658ce-7d91-44d3-acb2-8a76f19a3af7.png)

**Comment by xXBJXx** [comment]
Damit ist die automatische Helligkeitssteuerung gemeint, kannst du mir mal deine config aus `system.adapter.fully-tablet-control.0` hier reinposten

**Comment by xXBJXx** [comment]
Installiere mal die neue Version, da sollte die Meldung nicht mehr kommen v0.3.7

**Comment by duczz** [comment]
Top Dankeschön 

`{
  "mdmDisableVolumeButtons": false,
  "playMedia": false,
  "actionBarFgColor": -1,
  "deleteHistoryOnReload": false,
  "wifiSSID": "",
  "actionBarBgUrl": "",
  "mdmApkToInstall": "",
  "mdmDisableADB": true,
  "movementWhenUnplugged": false,
  "tabsBgColor": -2236963,
  "mqttDeviceInfoTopic": "$appId/deviceInfo/$deviceId",
  "errorUrlOnDisconnection": "0",
  "screensaverBrightness": "",
  "showActionBar": false,
  "mdmDisableScreenCapture": false,
  "restartOnCrash": true,
  "imageScaleType": "3",
  "deleteWebstorageOnReload": false,
  "forceDeviceAdmin": false,
  "kioskMode": false,
  "showStatusBar": false,
  "kioskWifiPinAction": "0",
  "knoxDisableAndroidBeam": false,
  "mqttBrokerUrl": "",
  "removeNavigationBar": false,
  "kioskAppWhitelist": "",
  "softKeyboard": true,
  "knoxDisableSettingsChanges": false,
  "kioskHomeStartURL": false,
  "knoxDisableSDCardWrite": false,
  "authPassword": "",
  "launchOnBoot": true,
  "movementStopsSleepOnPowerDisconnect": false,
  "knoxDisableUsbHostStorage": false,
  "inUseWhileAudioPlaying": false,
  "mdmPasswordQuality": "0",
  "resendFormData": false,
  "clearCacheEach": false,
  "sleepOnPowerConnect": false,
  "knoxDisableWiFi": false,
  "knoxDisableAirViewMode": false,
  "pauseMotionInBackground": false,
  "mqttBrokerPassword": "",
  "rootEnable": false,
  "resetZoomEach": false,
  "showHomeButton": true,
  "wifiMode": "0",
  "motionCameraId": "",
  "waitInternetOnReload": true,
  "knoxDisableWifiTethering": false,
  "knoxDisableBluetooth": false,
  "inUseWhileAnotherAppInForeground": false,
  "knoxDisableGoogleCrashReport": false,
  "geoLocationAccess": false,
  "mqttClientId": "",
  "knoxDisableVideoRecord": false,
  "barcodeScanTargetUrl": "",
  "enableUrlOtherApps": false,
  "showNavigationBar": false,
  "timeToScreenOffV2": "0",
  "loadCurrentPageOnReload": false,
  "lastVersionInfo": "1.47.2-play",
  "killOtherApps": false,
  "loadOverview": false,
  "remoteAdminScreenshot": true,
  "screenOnOnMotion": true,
  "useWideViewport": true,
  "enableTapSound": false,
  "clientCaPassword": "",
  "forceScreenOrientation": "0",
  "movementDetection": false,
  "progressBarColor": -13611010,
  "formAutoComplete": true,
  "webHostFilter": false,
  "screenOffOnPowerConnect": false,
  "advancedKioskProtection": true,
  "mdmLockTaskGlobalActions": true,
  "swipeTabs": false,
  "screensaverPlaylist": "",
  "webcamAccess": false,
  "screenBrightness": "0",
  "urlWhitelist": "",
  "enableQrScan": false,
  "launcherInjectCode": "",
  "timeToRegainFocus": "0",
  "knoxDisableClipboard": false,
  "cloudService": false,
  "initialScale": "0",
  "kioskExitGesture": "0",
  "wssServiceUrl": "",
  "barcodeScanIntent": "",
  "motionDetection": false,
  "resumeVideoAudio": true,
  "inUseWhileKeyboardVisible": false,
  "deviceName": "",
  "wifiEnterprisePassword": "",
  "remoteAdminCamshot": true,
  "bluetoothMode": "0",
  "reloadOnScreensaverStop": false,
  "forceSleepIfUnplugged": false,
  "actionBarInSettings": false,
  "timeToGoBackground": "0",
  "enablePopups": false,
  "screensaverOtherApp": false,
  "screensaverWallpaperURL": "fully://color#000000",
  "recreateTabsOnReload": false,
  "timeToClearSingleAppData": "0",
  "mdmDisableKeyguard": false,
  "forceScreenOrientationGlobal": false,
  "knoxHideStatusBar": false,
  "knoxDisableDeveloperMode": false,
  "addressBarBgColor": -2236963,
  "showAddressBar": false,
  "remoteAdminLan": true,
  "timeToShutdownOnPowerDisconnect": "0",
  "knoxDisableTaskManager": false,
  "knoxEnabled": false,
  "knoxDisableBackup": false,
  "reloadPageFailure": "0",
  "mdmLockTaskOverviewButton": false,
  "disableIncomingCalls": false,
  "cacheMode": "-1",
  "knoxDisableEdgeScreen": false,
  "forceHideKeyboard": false,
  "alarmSoundFileUrl": "",
  "mqttEventTopic": "$appId/event/$event/$deviceId",
  "disableNotifications": false,
  "folderCleanupTime": "",
  "disableOtherApps": true,
  "mdmDisableSafeModeBoot": true,
  "remoteAdminFileManagement": false,
  "knoxDisableMtp": false,
  "compassSensitivity": "50",
  "textSelection": false,
  "websiteIntegration": false,
  "motionFps": "5",
  "knoxDisableCellularData": false,
  "proximityScreenOff": false,
  "videoCaptureUploads": false,
  "reloadOnInternet": false,
  "enableLocalhost": false,
  "statusBarColor": 0,
  "usageStatistics": false,
  "isRunning": true,
  "resetWifiOnDisconnection": false,
  "sleepOnPowerDisconnectDelay": "0",
  "fileUploads": false,
  "singleAppMode": false,
  "launcherApps": "",
  "appLauncherBackgroundColor": -1,
  "reloadEachSeconds": "0",
  "forceImmersive": false,
  "mdmSystemAppsToEnable": "",
  "knoxDisableScreenCapture": false,
  "removeStatusBar": false,
  "knoxDisableWifiDirect": false,
  "knoxHideNavigationBar": false,
  "mdmDisableStatusBar": false,
  "folderCleanupList": "",
  "kioskWifiPin": "",
  "showShareButton": false,
  "webviewDarkMode": "1",
  "knoxDisableMultiUser": false,
  "redirectBlocked": false,
  "forceSwipeUnlock": false,
  "jsAlerts": true,
  "screensaverDaydream": false,
  "mdmDisableUsbStorage": false,
  "defaultWebviewBackgroundColor": -1,
  "batteryWarning": "0",
  "knoxDisableFactoryReset": false,
  "lockSafeMode": false,
  "kioskAppBlacklist": "",
  "keepOnWhileFullscreen": true,
  "graphicsAccelerationMode": "2",
  "wifiKey": "",
  "reloadOnScreenOn": false,
  "safeBrowsing": false,
  "barcodeScanBroadcastExtra": "",
  "deleteCookiesOnReload": false,
  "loadContentZipFileUrl": "",
  "sleepOnPowerDisconnect": false,
  "knoxDisableFirmwareRecovery": false,
  "knoxDisableVpn": false,
  "runInForeground": true,
  "screenOnOnMovement": true,
  "appLauncherScaling": "100",
  "barcodeScanInsertInputField": false,
  "motionSensitivity": "90",
  "knoxDisableHomeButton": false,
  "inactiveTabsBgColor": -4144960,
  "knoxDisableStatusBar": false,
  "knoxDisableHeadphoneState": false,
  "protectedContent": false,
  "accelerometerSensitivity": "80",
  "mqttBrokerUsername": "",
  "remoteFileMode": "0",
  "enableZoom": true,
  "playerCacheImages": true,
  "detectIBeacons": false,
  "navigationBarColor": 0,
  "mdmDisableAppsFromUnknownSources": true,
  "mainWebAutomation": "",
  "mdmMinimumPasswordLength": "5",
  "barcodeScanListenKeys": false,
  "screensaverOtherAppIntent": "",
  "clientCaUrl": "",
  "deleteCacheOnReload": false,
  "stopScreensaverOnMovement": true,
  "mdmApkToInstallInterval": "0",
  "knoxDisableOtaUpgrades": false,
  "fontSize": "100",
  "showQrScanButton": false,
  "motionDetectionAcoustic": false,
  "forceOpenByAppUrl": "",
  "stopScreensaverOnMotion": true,
  "audioRecordUploads": false,
  "timeToClearLauncherAppData": "0",
  "showAppLauncherOnStart": false,
  "mdmLockTaskNotifications": false,
  "disableScreenshots": false,
  "mdmAppLockTaskWhitelist": "",
  "actionBarSize": "100",
  "knoxDisableSafeMode": false,
  "ignoreMotionWhenScreensaverOnOff": false,
  "knoxDisableGoogleAccountsAutoSync": false,
  "knoxDisableAudioRecord": false,
  "volumeLevels": "",
  "showRefreshButton": false,
  "knoxDisableVolumeButtons": false,
  "autoImportSettings": true,
  "showForwardButton": true,
  "appToRunOnStart": "",
  "mqttEnabled": false,
  "motionSensitivityAcoustic": "90",
  "knoxDisablePowerSavingMode": false,
  "killAppsBeforeStartingList": "",
  "keepSleepingIfUnplugged": false,
  "userAgent": "0",
  "knoxDisableUsbDebugging": false,
  "injectJsCode": "",
  "disableVolumeButtons": true,
  "webviewMixedContent": "2",
  "environmentSensorsEnabled": false,
  "showNewTabButton": false,
  "errorURL": "",
  "authUsername": "",
  "showBackButton": true,
  "stopIdleReloadOnMotion": false,
  "enableBackButton": true,
  "ignoreSSLerrors": true,
  "webviewDebugging": false,
  "disableStatusBar": true,
  "volumeLimits": "",
  "confirmExit": true,
  "showProgressBar": true,
  "knoxDisableRecentTaskButton": false,
  "remotePdfFileMode": "0",
  "singleAppIntent": "",
  "knoxDisableClipboardShare": false,
  "knoxDisableBluetoothTethering": false,
  "urlBlacklist": "",
  "phoneSpeaker": false,
  "setWifiWakelock": true,
  "customUserAgent": "",
  "disableOutgoingCalls": false,
  "screenOffInDarkness": false,
  "actionBarCustomButtonUrl": "",
  "mdmSystemUpdatePolicy": "0",
  "knoxDisableAirplaneMode": false,
  "enablePullToRefresh": false,
  "touchInteraction": true,
  "enableFullscreenVideos": true,
  "appBlockReturnIntent": "",
  "localPdfFileMode": "0",
  "showTabCloseButtons": true,
  "showMenuHint": true,
  "keepScreenOnAdvanced": false,
  "disableHomeButton": true,
  "appLauncherTextColor": -16777216,
  "renderInCutoutArea": true,
  "pauseWebviewOnPause": false,
  "touchesOtherAppsBreakIdle": false,
  "movementBeaconList": "",
  "mdmApnConfig": "",
  "mdmRuntimePermissionPolicy": "0",
  "fadeInOutDuration": "200",
  "thirdPartyCookies": true,
  "showPrintButton": false,
  "mdmLockTaskSystemInfo": false,
  "keepScreenOn": false,
  "mdmProxyConfig": "",
  "knoxDisableMultiWindowMode": false,
  "volumeLicenseKey": "",
  "forceShowKeyboard": false,
  "actionBarBgColor": -15906911,
  "disableCamera": false,
  "showCamPreview": false,
  "addXffHeader": false,
  "displayMode": "0",
  "tabsFgColor": -16777216,
  "barcodeScanBroadcastAction": "",
  "remoteAdmin": true,
  "mdmLockTaskHomeButton": false,
  "webviewDragging": true,
  "forceScreenUnlock": true,
  "mdmAppsToDisable": "",
  "enableVersionInfo": true,
  "knoxDisableMicrophoneState": false,
  "knoxDisableUsbTethering": false,
  "appToRunInForegroundOnStart": "",
  "knoxDisableAirCommandMode": false,
  "reloadOnWifiOn": false,
  "sleepSchedule": "",
  "rebootTime": "",
  "actionBarTitle": "Fully Kiosk Browser",
  "webviewScrolling": true,
  "tapsToPinDialogInSingleAppMode": "7",
  "knoxDisableBackButton": false,
  "actionBarIconUrl": "",
  "wifiEnterpriseIdentity": "",
  "knoxActiveByKiosk": false,
  "timeToScreensaverV2": "0",
  "kioskWifiPinCustomIntent": "",
  "playAlarmSoundOnMovement": false,
  "barcodeScanSubmitInputField": false,
  "addRefererHeader": true,
  "startURL": "http://192.168.178.200:8082/jarvis/index.html",
  "remoteAdminSingleAppExit": false,
  "movementBeaconDistance": "5",
  "disablePowerButton": true,
  "showTabs": false,
  "microphoneAccess": false,
  "sebExamKey": "",
  "pageTransitions": false,
  "restartAfterUpdate": true,
  "swipeNavigation": false,
  "skipReloadIfStartUrlShowing": false,
  "launcherBgUrl": "",
  "knoxDisablePowerOff": false,
  "setRemoveSystemUI": false,
  "ignoreMotionWhenMoving": false,
  "searchProviderUrl": "https://www.google.com/search?q=",
  "setCpuWakelock": true,
  "playAlarmSoundUntilPin": false,
  "knoxDisableCamera": false,
  "desktopMode": false,
  "sebConfigKey": "",
  "cameraCaptureUploads": false,
  "wakeupOnPowerConnect": false,
  "autoplayAudio": false,
  "autoplayVideos": true,
  "knoxDisableNonMarketApps": false,
  "wifiType": "WPA_PSK",
  "darknessLevel": "10",
  "preventSleepWhileScreenOff": false,
  "mdmLockTask": false,
  "knoxDisablePowerButton": false,
  "readNfcTag": false,
  "kioskPinEnc": "enc_YL9VlN7ZMbWQJ2/DGhW59m0WilvTRf51x4cKGaZsC0k=",
  "remoteAdminPasswordEnc": "enc_ZLdXsbT+1RBjF7LFHSvc5bKs6hwQY/HnQwWrfEM6Jg8vDdgYlT6HZWDZ0A=="
}`
