### ISSUE TITLE
Snapshot

### ISSUE THREAD

**Issue by duczz** [xXBJXx/ioBroker.fully-tablet-control#419]
Hey,

bei mir funktioniert die camshot funktion nicht mehr, es wird kein bild mehr angelegt.

**Comment by xXBJXx** [comment]
Am Adapter wurde nichts gemacht, hast du ein Update vom Fully Kiosk Browser gemacht? Ich habe es gerade probiert mit Fully Kiosk Browser Version 1.49.3-play und da funktioniert es.
Adapter v0.3.8

![image](https://user-images.githubusercontent.com/32600934/217046286-af1e842a-e952-4d96-aa78-05cc5b771abd.png)
![image](https://user-images.githubusercontent.com/32600934/217046539-8ce4b49a-e6cc-48ab-80d9-2d55d6167a7f.png)

**Comment by duczz** [comment]
Hab den Fehler gefunden sorry.
Es muss Motion aktiv sein, damit ein camshot gemacht werden kann, wusst ich nicht, gibt's dafür einen grund?

**Comment by xXBJXx** [comment]
Das ist so von Fully Kiosk Browser vorgegeben da kann ich nichts machen

**Comment by duczz** [comment]
Okay, danke für die schnelle hilfe
