### ISSUE TITLE
Fully Kiosk Browser reagiert nicht

### ISSUE THREAD

**Issue by valbuz** [xXBJXx/ioBroker.fully-tablet-control#422]
**Describe the bug**  
Zeitweise erscheint ein kleines Pop-Up mit der Aufschrift: Fully Kiosk Browser reagiert nicht
Ich kann dann den Fully Schliessen/warten und Feedback senden.
Die App schwint jedoch im Hintergrund normal weiter zu laufen, trotzdes Pop-Up's

**To Reproduce**  
Kommt von alleine in unterschiedlichen Zeitabständen

**Expected behavior**  

**Screenshots & Logfiles**  
![fully](https://user-images.githubusercontent.com/35503440/223062198-5e6aefdd-c28b-4774-90a2-cfc6424bf087.PNG)

**Versions:**  
 - Adapter version: v0.3.6-1
 - JS-Controller version: 4.0.24
 - Node version: v16.19.0
 - Operating system: ubuntu 20.04.

**Additional context**  
Alle Updates auf dem Tablet wurden gemacht.
Tablet: Samsung 
Tab A SM-T510

**Comment by xXBJXx** [comment]
Der Adapter hat nichts mit der app zu tun das ist ein Problem von der App und nicht mit dem Adapter.

**Comment by valbuz** [comment]
Sorry, logisch :-)
