### ISSUE TITLE
Immer wieder Request Probleme

### ISSUE THREAD

**Issue by canim60** [xXBJXx/ioBroker.fully-tablet-control#52]
Dein Adapter an sich läuft, aber bekommen öfters die Fehlermeldung

`

fully-tablet-control.0 | 2020-09-20 15:36:07.418 | error | (21243) [Request] Smarthome Unable to contact: Error: connect  ECONNREFUSED 192.168.2.101:2323 \| Error: connect ECONNREFUSED  192.168.2.101:2323
-- | -- | -- | --
fully-tablet-control.0 | 2020-09-20 15:36:05.577 | error | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
fully-tablet-control.0 | 2020-09-20 15:36:05.577 | error | (21243) Smarthome [ScreensaverOnBri] could not be sent: connect  ECONNREFUSED 192.168.2.101:2323, stack: Error: connect ECONNREFUSED  192.168.2.101:2323
fully-tablet-control.0 | 2020-09-20 15:36:05.576 | error | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
fully-tablet-control.0 | 2020-09-20 15:36:05.576 | error | (21243) Smarthome [nightBri] could not be sent: connect ECONNREFUSED  192.168.2.101:2323, stack: Error: connect ECONNREFUSED  192.168.2.101:2323

`

hat definitiv mit der Helligkeit zu tun, kannst du damit was anfangen?

`Platform: linux
os: linux
Architecture: arm
CPUs: 4
Speed: 1600 MHz
Model: ARMv7 Processor rev 3 (v7l)
RAM: 3.7 GB 
System uptime: 1 T. 22:52:53
Node.js: v12.18.4
NPM: 6.14.6
Disk size: 14.3 GiB
Disk free: 10.6 GiB
adapters count: 364
Uptime: 1 T. 22:52:48
Active instances: `19``

**Comment by xXBJXx** [comment]
Dein Tablet hat Verbindung Probleme er braucht zu lange um zu antworten da must du mal schauen wie die Verbindung von dem device wo iobroker läuft zu deinem Tablet ist ping usw.

**Comment by canim60** [comment]
Tablet ist hinter der Wand vom Router Sprich entfernung von 40cm. Habs mal angepingt,

> Antwort von 192.168.2.101: Bytes=32 Zeit=112ms TTL=64
Antwort von 192.168.2.101: Bytes=32 Zeit=130ms TTL=64
Antwort von 192.168.2.101: Bytes=32 Zeit=151ms TTL=64
Antwort von 192.168.2.101: Bytes=32 Zeit=171ms TTL=64

schön sind die Werte nicht..., nen guten Fritzbox kann ich leider nicht nehmen. Telekom Hybrid leider. ist eine feste Ip hinterlegt. 

Kann man die Antwortzeit vergrößern?

**Comment by xXBJXx** [comment]
> Kann man die Antwortzeit vergrößern?

das weiß ich leider nicht
