### ISSUE TITLE
Kein Werteupdate in iobroker

### ISSUE THREAD

**Issue by Parodontitis** [xXBJXx/ioBroker.fully-tablet-control#55]
Seit Fully Kiosk Browser **1.40.3** werden die Werte in den DP nicht mehr aktualisiert. Nur beim Adapter-Start, danach kein Update mehr.  In der Version 1.41 das gleiche. Ein Downgrade auf 1.42 hilft. Gleiches Verhalten in FullyBrowser Adapter.

Versionen:
fully-tablet-control 0.2.10
fullyBrowser 2.0.1

[Siehe Forum](https://forum.iobroker.net/topic/36993/fullybrowser-keine-aktualisierung-der-dp)

**Comment by xXBJXx** [comment]
ich habe auf meinem Test System V 1.40.2 / 1.40.3 und 1.41 und auf Hauptsystem die Version 1.41 laufen mit der Adapter Version 0.2.15 und es wird alles aktualisiert alle 30 sec so wie eingestellt.
Ich kann das also nicht nachvollziehen oder reproduzieren. 
Auf was hast du den dein Intervall gestellt ?

**Comment by xXBJXx** [comment]
mit Adapter Version 0.2.15 funktioniert die aktualisiert [Siehe Forum](https://forum.iobroker.net/topic/36993/fullybrowser-keine-aktualisierung-der-dp/12)
