### ISSUE TITLE
Seite Ladegerät

### ISSUE THREAD

**Issue by Ilovegym66** [xXBJXx/ioBroker.fully-tablet-control#7]
Hi,
wenn man unter anderem Tablets hat, die nicht an einer schaltbaren Steckdose hängen, diese aber eine geringere Nummer in der Konfig des Adapters haben, als welche, die geschaltet werden, dann muss ich diese ja trotzdem eintragen um auf die höhere Nummer des Tablets zu kommen.
Danach streikt der Adapter mit Fehlermeldungen, da er logischerweise keinen Datenpunkt der Steckdose gefunden hat. 
Siehe [Forum](https://forum.iobroker.net/post/444072)

Mein Vorschlag wäre, hier entweder die Auswahl der Tablets anders zu machen ( auch für die anderen Konfigseiten ), dass man ein Tablet aus der Hauptseite frei auswählen kann, und dann in der jeweiligen Konfigseite dies für Funktionen einträgt, die es auch hat oder bekommen soll.
( nicht alle werden auch über Bewegungsmelder gesteuert, da ist dann gleich das nächste gleiche Problem..) 

Bei der Helligkeitsregelung ähnlich, da kann man mit Checkmarks die Funktion auswählen. 
( dies bitte nochmal auch checken, hatte letzt ein Problem, war kein Haken gesetzt und das Tablet hat sich trotzdem abgeschaltet..)

Vielleicht aber auch einfach nochmal das Design der Zuordnung Tablet-Konfigseite überdenken. Bei mehr als 10 Stück wirds sonst unübersichtlich..
Vielleicht hab ich das auch nicht richtig verstanden und es ist viel einfacher?

**Comment by xXBJXx** [comment]
Ich habe die Lade Steuerung angepasst:

Lademodus auswählbar sind **Dauerstrom** oder **Ladezyklus** bei beiden muss die **ID eingetragen sein**  bei Dauerstrom wird das Tablet dauerhaft am Strom gehalten und bei Ladezyklus wird das Tablet z.B. bei 20% anfangen zu laden und bei 85% das Laden abschalten. \
Bei der Auswahl **aus** wird die Ladesteuerung für dieses Tablet ausgeschaltet es muss auch keine **ID** eingetragen werden.
![charger-mode](https://user-images.githubusercontent.com/32600934/83981899-5f3c7000-a922-11ea-813a-887af13656ee.png)


>Bei der Helligkeitsregelung ähnlich, da kann man mit Checkmarks die Funktion auswählen.
( dies bitte nochmal auch checken, hatte letzt ein Problem, war kein Haken gesetzt und das Tablet hat sich trotzdem abgeschaltet..)

die Helligkeitsregelung funktioniert in meinen Tests und bei mir zuhause so wie es soll. 


>Vielleicht aber auch einfach nochmal das Design der Zuordnung Tablet-Konfigseite überdenken

die Zuordnung ist in dieser Form am einfachsten jede Tabelle fängt mit 0 an im Adapter läuft da eine Schleife über die Tabellen, das heißt Tabelle 1 ist überall die Tabelle 1.

Bei den Bewegungsmelder ist es anders dort ist es so dass wen nur ein Bewegungsmelder eingetragen ist es dann für alle benutzt wird sobald es dann mehr als 1 wird **Muss** für jedes Tablet ein Bewegungsmelder angelegt werden diese könne auch deaktiviert werden wen nicht benötigt.
