### ISSUE TITLE
Fehlermeldung bei Aktivierung der Instanz

### ISSUE THREAD

**Issue by CKMartens** [xXBJXx/ioBroker.fully-tablet-control#9]
Bei Aktivierung der Instanz kommt zur Zeit folgende Meldung:

```
fully-tablet-control.0 | 2020-06-09 07:38:33.461 | error | at process._tickCallback (internal/process/next_tick.js:68:7)
-- | -- | -- | --
fully-tablet-control.0 | 2020-06-09 07:38:33.461 | error | at FullyTabletControl.initialization (/opt/iobroker/node_modules/iobroker.fully-tablet-control/main.js:255:59)
fully-tablet-control.0 | 2020-06-09 07:38:33.461 | error | (28248) [initialization] : Cannot read property 'minute' of undefined, stack: TypeError: Cannot read property 'minute' of undefined
fully-tablet-control.0 | 2020-06-09 07:38:35.257 | warn | (28248) 09.06.20 07:38 VIS_WZ Tablet charging function has detected a malfunction, the tablet is not charging, please check it !!!
-- | -- | -- | --
fully-tablet-control.0 | 2020-06-09 07:38:35.257 | info | (28248) VIS_WZ Loading started
fully-tablet-control.0 | 2020-06-09 07:38:35.203 | warn | (28248) 09.06.20 07:38 VIS_Wetter Tablet charging function has detected a malfunction, the tablet is not charging, please check it !!!
fully-tablet-control.0 | 2020-06-09 07:38:35.202 | info | (28248) VIS_Wetter Loading started
```
Eingestellt sind die folgenden Ladegeräte:
![image](https://user-images.githubusercontent.com/19702758/84110526-57192900-aa25-11ea-90bb-54165bce63a8.png)

Und die angegebenen Steckdosen sind erreichbar:
![image](https://user-images.githubusercontent.com/19702758/84110323-eeca4780-aa24-11ea-9941-5d5037d57f5f.png)
![image](https://user-images.githubusercontent.com/19702758/84110454-37820080-aa25-11ea-8d62-22f50a40412d.png)

NodeJS 10.21.0
Adapter Version: 0.2.7
js-Controller: 3.1.5

**Comment by xXBJXx** [comment]
was hast du die anderen Einstellungen eingestellt (Helligkeit, Bildschirmschoner usw.) und wen ja wie ?

```
fully-tablet-control.0 | 2020-06-09 07:38:33.461 | error | at process._tickCallback (internal/process/next_tick.js:68:7)
fully-tablet-control.0 | 2020-06-09 07:38:33.461 | error | at FullyTabletControl.initialization (/opt/iobroker/node_modules/iobroker.fully-tablet-control/main.js:255:59)
fully-tablet-control.0 | 2020-06-09 07:38:33.461 | error | (28248) [initialization] : Cannot read property 'minute' of undefined, stack: TypeError: Cannot read property 'minute' of undefined#
```

das kommt immer dann wen der Bildschirmschoner in der config Seite an ist aber kein Eintrag erstellt wurde z.b. so
![Screenshot_193](https://user-images.githubusercontent.com/32600934/84162236-6f626580-aa70-11ea-9d98-4aef745665f7.png)

und so sohlte es aussehen 
![Screenshot_194](https://user-images.githubusercontent.com/32600934/84162394-9faa0400-aa70-11ea-93b9-36ae8e808db4.png)



```
fully-tablet-control.0 | 2020-06-09 07:38:35.257 | warn | (28248) 09.06.20 07:38 VIS_WZ Tablet charging function has detected a malfunction, the tablet is not charging, please check it !!!
```

das bedeutet nur das dein Tablett unter 18% Battery gesunken ist und nicht laden tut.

```
fully-tablet-control.0 | 2020-06-09 07:38:35.257 | info | (28248) VIS_WZ Loading started
```

das bedeutet nur das dein Tablett angefangen hat zu laden

**Comment by CKMartens** [comment]
Meine Settings für Helligkeit ist:
![image](https://user-images.githubusercontent.com/19702758/84172470-5790de80-aa7c-11ea-85ae-0f0d0668ce66.png)

Aber der Bildschirmschoner war tatsächlich eingeschaltet. 

Nach Deaktivierung hat die Instanz ohne Fehler durchgestartet. Danke Dir für Deine Hilfe
