### ISSUE TITLE
push actual version to latest or stable

### ISSUE THREAD

**Issue by Ilovegym66** [xXBJXx/ioBroker.fully-tablet-control#93]
since more as 4 weeks the actual Version beta-5 is working fine, think about to push the version to stable, please.
:-)

**Comment by xXBJXx** [comment]
I don't know if I should do this again, the endless waiting for the pull request to be taken care of. With 2 adapters that I had put in, I withdrew the request again, the pull request was open for 6 months and since September 9th there had been no more action I didn't want to wait anymore and closed and withdrawn it.

Therefore, I am thinking about whether I should do it.
I will let you know here if I let you do it in the repo or not.

**Comment by Apollon77** [comment]
@xXBJXx I'm very sorry (again) that this happened but times are hard and reviews need time. We are current at the moment, so revieews do not need that long ;-)

**Comment by Apollon77** [comment]
PS: ANd I gave review feedback some days after you closed it ... go ahead and bring your stuff :-)

**Comment by o0shojo0o** [comment]
Go @xXBJXx give yourself a jerk, the adapter is good and belongs in the repository ;)

**Comment by Feuer-sturm** [comment]
I would be happy as well if this adapter is available in beta/stable :-)

**Comment by xXBJXx** [comment]
@Feuer-sturm 
I am currently working on a new config page as soon as it is finished and the adapter is adapted to it I will put it into the beta but this could take a while as I have a lot to do at work at the moment and hardly get to program it 

this is how it could look in the end
![newGui](https://user-images.githubusercontent.com/32600934/122655407-56e05d00-d152-11eb-9d6b-9361a057b0b9.png)

**Comment by Feuer-sturm** [comment]
@xXBJXx Thanks for the feedback :-)

**Comment by macpo** [comment]
I would also love it if the adapter was in the official ioBroker repository.

**Comment by xXBJXx** [comment]
@macpo The adapter is currently being completely rebuilt, as soon as that is finished it will also be added to the repository

**Comment by macpo** [comment]
I saw it and wanted to give you an additional feedback, that there are more people who like your work and think it is worth to be found easier by more people.

**Comment by Ilovegym66** [comment]
looks like adapter not maintained any more. Issue closed.

**Comment by mcm1957** [comment]
> looks like adapter not maintained any more. Issue closed.

**Sorry to say 'yes you're right'.**
xXBJXx cannot maintain it's adapters any longer - at least currently. We all hope, that he will continue his great work later - but this cannot be estimated currently.

Please take a look at ioBroker.fullybrowser (https://github.com/arteck/iobroker.fullyBrowser). Maybe this adapter can help.
If not, please raise a issue at fullyBrowser, mayb arteck can enhance  its adapter.

At least I could transfer this adapter to iobroker-community-adapters. BUT I will not have sufficicent time to enhance it or to fix problems. So we would need to check if this is an option first.
