### ISSUE TITLE
Keine Datenanzeige im iOBroker unter Objekt fullybrowser

### ISSUE THREAD

**Issue by rde29** [xXBJXx/ioBroker.fully-tablet-control#96]
**Describe the bug**  
Nutze iOBroker und Fullybrowser Adapter nun seit 2-3 Wochen. Habe den Akkustand meines Tablets über Script abgefragt. Die Daten wurden mir dann unter Objekte unterhalb Fullybrowser angezeigt und angelegt. Das Funkioniert aber nicht mehr. Auch durch Neuinstallation eines separten raspbeery Pi und ioBroker und Adaptern klappt das nicht mehr. Ich kann also die Datenabfragen, die Ergebnisse werden aber nicht mehr unter Objekte unterhalb der Tablet-IP angezeigt. In Foren habe ich sämtlich Tips befolgt ohne Erfolg

Script
Script

var request = require('request');
var link = "http://<IP-Tablet>:2323/?cmd=deviceInfo&type=json&password=<PW>";
var state = "javascript.0.Allgemein.Akku_Tablet"/*Akku_Tablet*/;

function fully() {
    request(link, function(error,response, body) {
        if(error) log('Fehler request: ' + error, 'error');
        else {
            log(body);  /*neu*/
            objects = JSON.parse(body);
            bat = objects.batteryLevel;
            setState(state, bat);
            log ("batteryLevel = " + bat); /*geändert*/
        }    
    });
}
Script Ergebnis:
{"deviceName":"Fire Tablet","altitude":0,"locationProvide":"network","batteryLevel":72,"isPlugged":true,"SSID":"\"xxx\"","Mac":"xxx","ip4":"192.168.xx","ip6":"xxx","hostname4":"unknown","hostname6":"unknown","wifiSignalLevel":9,"isMobileDataEnabled":false,"screenOrientation":270,"screenBrightness":8,"screenLocked":false,"screenOn":true,"batteryTemperature":29,"plugged":true,"keyguardLocked":false,"locale":"de_DE","serial":"unknown","build":"PS7317","androidVersion":"9","webviewUA":"Mozilla/5.0 (Linux; Android 9; KFMAWI Build/PS7317; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/84.0.4147.125 Safari/537.36","motionDetectorStatus":2,"isDeviceAdmin":true,"isDeviceOwner":false,"internalStorageFreeSpace":24374050816,"internalStorageTotalSpace":26514579456,"ramUsedMemory":1279397888,"ramFreeMemory":599244800,"ramTotalMemory":1878642688,"appUsedMemory":6794976,"appFreeMemory":395858208,"appTotalMemory":402653184,"displayHeightPixels":1200,"displayWidthPixels":1920,"isMenuOpen":false,"topFragmentTag":"","isInDaydream":false,"isRooted":false,"isLicensed":true,"isInScreensaver":false,"kioskLocked":false,"isInForcedSleep":false,"maintenanceMode":false,"kioskMode":false,"startUrl":"http://192.168.178.72:8084/vis/index.html?RDE-Tablett#Start","currentTabIndex":0,"mqttConnected":false,"deviceID":"8a2e6a19-52f15a22","locationLatitude":48.07521135080606,"locationLongitude":11.701114196330312,"appVersionCode":875,"appVersionName":"1.42.5","androidSdk":28,"deviceModel":"KFMAWI","deviceManufacturer":"Amazon","foregroundApp":"de.ozerov.fully","currentPage":"http://192.168.178.72:8084/vis/index.html?RDE-Tablett#Start","lastAppStart":"10.12.20 19:51:58","sensorInfo":[{"type":5,"name":"LIGHT","vendor":"MTK","version":1,"accuracy":3,"values":[0],"lastValuesTime":1607664979466,"lastAccuracyTime":1607626318857}]}

Die Daten wurden mir dann unter fullybrowser0/IP-Adresse/batteryLEvel ,...... angezeigt --> Dies ist nicht mehr der Fall

**Comment by xXBJXx** [comment]
Das hier ist nicht der Fullybrowser Adapter, sondern der fully-tablet-control und da funktioniert alles hab es selbst auf 3 Tablets laufen die BatteryLevel werden ordnungsgemäß abgerufen und in die Objekte geschrieben. 
Dein Code habe ich auch ausprobiert und er funktioniert auch wie es soll.
wenn du Lust hast können wir uns im Discord treffen und schauen dann wo bei dir das Problem liegen kann
hier der [Discord Server](https://discord.com/invite/HwUCwsH)

**Comment by rde29** [comment]
Hallo, würde deine Hilfe geren entgegennehmen,

 

wie kann ich dich in Discord kontaktieren, da ich das Ganze nicht kenne

Gruß

rde

 

Von: xXBJXx <notifications@github.com> 
Gesendet: Freitag, 11. Dezember 2020 14:19
An: xXBJXx/ioBroker.fully-tablet-control <ioBroker.fully-tablet-control@noreply.github.com>
Cc: rde29 <ralph.decker@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [xXBJXx/ioBroker.fully-tablet-control] Keine Datenanzeige im iOBroker unter Objekt fullybrowser (#96)

 

Das hier ist nicht der Fullybrowser Adapter, sondern der fully-tablet-control und da funktioniert alles hab es selbst auf 3 Tablets laufen die BatteryLevel werden ordnungsgemäß abgerufen und in die Objekte geschrieben.
Dein Code habe ich auch ausprobiert und er funktioniert auch wie es soll.
wenn du Lust hast können wir uns im Discord treffen und schauen dann wo bei dir das Problem liegen kann
hier der Discord Server <https://discord.com/invite/HwUCwsH>

**Comment by xXBJXx** [comment]
in Discord ein Account machen auf den link klicken dann kommst du in den Iobroker Discord da kannst du mich (Issi) in der unser liste anschreiben oder wenn ich im sprach Kanal bin einfach reinkommen dann können wir da drüber reden
